// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfdxwckcfieyxipsvazl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZHh3Y2tjZmlleXhpcHN2YXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTg3MjAsImV4cCI6MjA2ODk3NDcyMH0.p7N9OxjuQLGS85xboI0no7aU_86J4RhHxBwhe2zmj9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});